name: Build and upload development artifacts

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  version:
    name: Describe
    uses: ./.github/workflows/build-umu-version.yml

  fedora40-build:
    name: Fedora 40 Build
    uses: ./.github/workflows/build-umu-fedora-40.yml
    needs: version
    with:
      version: ${{ needs.version.outputs.version }}
      shasum: ${{ github.sha }}

  fedora41-build:
    name: Fedora 41 Build
    uses: ./.github/workflows/build-umu-fedora-41.yml
    needs: version
    with:
      version: ${{ needs.version.outputs.version }}
      shasum: ${{ github.sha }}

  debian12-build:
    name: Debian 12 Build
    uses: ./.github/workflows/build-umu-debian-12.yml
    needs: version
    with:
      version: ${{ needs.version.outputs.version }}

  debian13-build:
    name: Debian 13 Build
    uses: ./.github/workflows/build-umu-debian-13.yml
    needs: version
    with:
      version: ${{ needs.version.outputs.version }}

  ubuntu-noble-build:
    name: Ubuntu 24.04 Build
    uses: ./.github/workflows/build-umu-ubuntu-noble.yml
    needs: version
    with:
      version: ${{ needs.version.outputs.version }}

  zipapp-build:
    name: Zipapp Build
    uses: ./.github/workflows/build-umu-zipapp.yml
    needs: version
    with:
      version: ${{ needs.version.outputs.version }}
