name: umu-launcher

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        # tomllib requires Python 3.11
        # Ubuntu latest (Jammy) provides Python 3.10
        version: ["3.10", "3.11", "3.12", "3.13"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install ruff
        pip install python-xlib
        pip install filelock
    - name: Lint umu_*.py files with Ruff
      run: |
        pip install ruff
        ruff check --output-format github ./umu/umu_*.py
    - name: Test with unittest
      run: python3 ./umu/umu_test.py
    - name: Test with unittest for plugins
      if: ${{ matrix.version == '3.11' || matrix.version == '3.12' || matrix.version == '3.13' }}
      run: python3 ./umu/umu_test_plugins.py
